SELECT a.TITLE, a.BOARD_ID,	b.REPLY_ID, b.WRITER_ID, b.CONTENTS, TO_CHAR(b.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_REPLY b on a.BOARD_ID = b.BOARD_ID
WHERE EXTRACT(YEAR FROM a.CREATED_DATE) = 2022 AND EXTRACT(MONTH FROM a.CREATED_DATE) = 10
ORDER BY b.CREATED_DATE ASC, a.TITLE ASC;